version: 2 # use CircleCI 2.0

references:
  # Configuration
  workspace: &workspace
    ~/xcov_report
  
  docker_image: &docker_image
    circleci/ruby:2.4-node

  container_config: &container_config
    docker:
      - image: *docker_image
    working_directory: *workspace

  # Dependencies
  install_dependencies: &install_dependencies
    run:
      name: Update the project dependencies
      command: bundle install

  # Build
  build: &build
    run:
      name: Gem build
      command: gem build fastlane-plugin-xcov_report.gemspec

  # Tests
  unit_test: &unit_test
    run:
      name: Run unit tests
      command: bundle exec rake

jobs:
  test:
    <<: *container_config

    steps:
      - checkout
      - *install_dependencies
      - *unit_test

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test