version: 2 # use CircleCI 2.0

references:
  # Configuration
  workspace: &workspace
    ~/xcov_report
  
  docker_image: &docker_image
    circleci/ruby:2.4-node

  container_config: &container_config
    docker:
      - image: *docker_image
    working_directory: *workspace

  # Dependencies
  install_dependencies: &install_dependencies
    run:
      name: Update the project dependencies
      command: |
        bundle install
        npm install

  # Build
  build: &build
    run:
      name: Gem build
      command: gem build fastlane-plugin-xcov_report.gemspec
  
  # Handle cache
  build_key: &build_key
    build-app-{{ .Environment.CIRCLE_WORKFLOW_ID }}

  store_build_cache: &store_build_cache
    save_cache:
      key: *build_key
      paths:
        - ./*.gem
  
  restore_build_cache: &restore_build_cache
    restore_cache:
      key: *build_key

  # Tests
  unit_test: &unit_test
    run:
      name: Run unit tests
      command: npm test

jobs:
  test:
    <<: *container_config

    steps:
      - checkout
      - *install_dependencies
      - *unit_test

  build:
    <<: *container_config

    steps:
      - checkout
      - *install_dependencies
      - *build
      - *store_build_cache

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
      - build:
          filters:
            branches:
              ignore:
                - master